
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEASSIGN DIVIDE EQUALS EQV GT IDENTIFIER LPAREN LT MINUS MOD NUMBER PLUS PRINT RPAREN SEMICOLON TIMESprogram : expr\n               | empty\n               | assignempty : assign : IDENTIFIER EQUALS expr\n              | IDENTIFIER EQUALS IDENTIFIERexpr : expr PLUS expr\n            | expr MINUS expr\n            | expr DIVIDE expr\n            | expr TIMES expr\n            | expr MOD expr\n            | expr LT expr\n            | expr GT expr\n            | expr EQV exprexpr : LPAREN expr RPARENexpr : NUMBERexpr : IDENTIFIERexpr : PRINT expr'
    
_lr_action_items = {'LPAREN':([0,5,8,9,10,11,12,13,14,15,16,19,],[5,5,5,5,5,5,5,5,5,5,5,5,]),'NUMBER':([0,5,8,9,10,11,12,13,14,15,16,19,],[6,6,6,6,6,6,6,6,6,6,6,6,]),'IDENTIFIER':([0,5,8,9,10,11,12,13,14,15,16,19,],[7,18,18,18,18,18,18,18,18,18,18,30,]),'PRINT':([0,5,8,9,10,11,12,13,14,15,16,19,],[8,8,8,8,8,8,8,8,8,8,8,8,]),'$end':([0,1,2,3,4,6,7,18,20,21,22,23,24,25,26,27,28,29,30,31,],[-4,0,-1,-2,-3,-16,-17,-17,-18,-7,-8,-9,-10,-11,-12,-13,-14,-15,-6,-5,]),'PLUS':([2,6,7,17,18,20,21,22,23,24,25,26,27,28,29,30,31,],[9,-16,-17,9,-17,9,-7,-8,-9,-10,9,9,9,9,-15,-17,9,]),'MINUS':([2,6,7,17,18,20,21,22,23,24,25,26,27,28,29,30,31,],[10,-16,-17,10,-17,10,-7,-8,-9,-10,10,10,10,10,-15,-17,10,]),'DIVIDE':([2,6,7,17,18,20,21,22,23,24,25,26,27,28,29,30,31,],[11,-16,-17,11,-17,11,11,11,-9,-10,11,11,11,11,-15,-17,11,]),'TIMES':([2,6,7,17,18,20,21,22,23,24,25,26,27,28,29,30,31,],[12,-16,-17,12,-17,12,12,12,-9,-10,12,12,12,12,-15,-17,12,]),'MOD':([2,6,7,17,18,20,21,22,23,24,25,26,27,28,29,30,31,],[13,-16,-17,13,-17,13,-7,-8,-9,-10,13,13,13,13,-15,-17,13,]),'LT':([2,6,7,17,18,20,21,22,23,24,25,26,27,28,29,30,31,],[14,-16,-17,14,-17,14,-7,-8,-9,-10,14,14,14,14,-15,-17,14,]),'GT':([2,6,7,17,18,20,21,22,23,24,25,26,27,28,29,30,31,],[15,-16,-17,15,-17,15,-7,-8,-9,-10,15,15,15,15,-15,-17,15,]),'EQV':([2,6,7,17,18,20,21,22,23,24,25,26,27,28,29,30,31,],[16,-16,-17,16,-17,16,-7,-8,-9,-10,16,16,16,16,-15,-17,16,]),'RPAREN':([6,17,18,20,21,22,23,24,25,26,27,28,29,],[-16,29,-17,-18,-7,-8,-9,-10,-11,-12,-13,-14,-15,]),'EQUALS':([7,],[19,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'expr':([0,5,8,9,10,11,12,13,14,15,16,19,],[2,17,20,21,22,23,24,25,26,27,28,31,]),'empty':([0,],[3,]),'assign':([0,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> expr','program',1,'p_program','interpy.py',40),
  ('program -> empty','program',1,'p_program','interpy.py',41),
  ('program -> assign','program',1,'p_program','interpy.py',42),
  ('empty -> <empty>','empty',0,'p_empty','interpy.py',46),
  ('assign -> IDENTIFIER EQUALS expr','assign',3,'p_assign','interpy.py',50),
  ('assign -> IDENTIFIER EQUALS IDENTIFIER','assign',3,'p_assign','interpy.py',51),
  ('expr -> expr PLUS expr','expr',3,'p_expr','interpy.py',55),
  ('expr -> expr MINUS expr','expr',3,'p_expr','interpy.py',56),
  ('expr -> expr DIVIDE expr','expr',3,'p_expr','interpy.py',57),
  ('expr -> expr TIMES expr','expr',3,'p_expr','interpy.py',58),
  ('expr -> expr MOD expr','expr',3,'p_expr','interpy.py',59),
  ('expr -> expr LT expr','expr',3,'p_expr','interpy.py',60),
  ('expr -> expr GT expr','expr',3,'p_expr','interpy.py',61),
  ('expr -> expr EQV expr','expr',3,'p_expr','interpy.py',62),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_paren','interpy.py',66),
  ('expr -> NUMBER','expr',1,'p_expr_number','interpy.py',70),
  ('expr -> IDENTIFIER','expr',1,'p_expr_identifier','interpy.py',74),
  ('expr -> PRINT expr','expr',2,'p_expr_print','interpy.py',78),
]
