
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN DIVIDE EQUALS EQV GT GTE IDENTIFIER LPAREN LT LTE MINUS MOD NUMBER PLUS PRINT RPAREN SEMICOLON TIMESprogram : expr\n               | emptyempty : assign : IDENTIFIER EQUALS exprexpr : expr PLUS expr\n            | expr MINUS expr\n            | empty\n            | NUMBER'
    
_lr_action_items = {'NUMBER':([0,5,6,],[4,4,4,]),'$end':([0,1,2,3,4,5,6,7,8,9,],[-3,0,-1,-2,-8,-3,-3,-5,-7,-6,]),'PLUS':([0,2,3,4,5,6,7,8,9,],[-3,5,-7,-8,-3,-3,5,-7,5,]),'MINUS':([0,2,3,4,5,6,7,8,9,],[-3,6,-7,-8,-3,-3,6,-7,6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'expr':([0,5,6,],[2,7,9,]),'empty':([0,5,6,],[3,8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> expr','program',1,'p_program','interpy.py',42),
  ('program -> empty','program',1,'p_program','interpy.py',43),
  ('empty -> <empty>','empty',0,'p_empty','interpy.py',47),
  ('assign -> IDENTIFIER EQUALS expr','assign',3,'p_assign','interpy.py',51),
  ('expr -> expr PLUS expr','expr',3,'p_expr','interpy.py',55),
  ('expr -> expr MINUS expr','expr',3,'p_expr','interpy.py',56),
  ('expr -> empty','expr',1,'p_expr','interpy.py',57),
  ('expr -> NUMBER','expr',1,'p_expr','interpy.py',58),
]
